INSERT INTO currencies (country_code, worth) VALUES ('AndorraEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('Antigua and BarbudaEast Caribbean Dollar (XCD)',2.4153);
INSERT INTO currencies (country_code, worth) VALUES ('ArgentinaArgentine Peso (ARS)',13.8789);
INSERT INTO currencies (country_code, worth) VALUES ('ArubaAruban Florin (AWG)',1.6110);
INSERT INTO currencies (country_code, worth) VALUES ('AustraliaAustralian Dollar (AUD)',1.1855);
INSERT INTO currencies (country_code, worth) VALUES ('AustriaEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('BahrainBahraini Dinar (BHD)',0.3324);
INSERT INTO currencies (country_code, worth) VALUES ('BarbadosBarbadian Dollar (BBD)',1.7936);
INSERT INTO currencies (country_code, worth) VALUES ('BelgiumEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('BelizeBelize Dollar (BZD)',1.8000);
INSERT INTO currencies (country_code, worth) VALUES ('BermudaBermuda - Dollar - BMD (BMD)',0.9000);
INSERT INTO currencies (country_code, worth) VALUES ('BrazilBrazilian Real (BRL)',3.0404);
INSERT INTO currencies (country_code, worth) VALUES ('Brunei DarussalamBrunei Dollar (BND)',1.2701);
INSERT INTO currencies (country_code, worth) VALUES ('BulgariaBulgarian Lev (BGN)',1.6409);
INSERT INTO currencies (country_code, worth) VALUES ('CanadaCanadian Dollar (CAD)',1.1957);
INSERT INTO currencies (country_code, worth) VALUES ('Cayman IslandsCayman Islands Dollar (KYD)',0.7380);
INSERT INTO currencies (country_code, worth) VALUES ('ChileChilean Peso (CLP)',591.5686);
INSERT INTO currencies (country_code, worth) VALUES ('ChinaChinese Renminbi (CNY)',6.0835);
INSERT INTO currencies (country_code, worth) VALUES ('ColombiaColombian Peso (COP)',2589.5493);
INSERT INTO currencies (country_code, worth) VALUES ('Costa RicaCosta Rican Colon (CRC)',477.1884);
INSERT INTO currencies (country_code, worth) VALUES ('CroatiaCroatian Kuna (HRK)',6.3160);
INSERT INTO currencies (country_code, worth) VALUES ('CyprusEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('Czech RepublicCzech Koruna (CZK)',22.2943);
INSERT INTO currencies (country_code, worth) VALUES ('DenmarkDanish Krone (DKK)',6.2802);
INSERT INTO currencies (country_code, worth) VALUES ('Dominican RepublicDominican Peso (DOP)',39.8496);
INSERT INTO currencies (country_code, worth) VALUES ('EstoniaEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('European UnionEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('FijiFijian Dollar (FJD)',1.7306);
INSERT INTO currencies (country_code, worth) VALUES ('FinlandEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('FranceEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('French PolynesiaCFP Franc (XPF)',91.0630);
INSERT INTO currencies (country_code, worth) VALUES ('GermanyEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('GreeceEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('GuadeloupeEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('GuatemalaGuatemalan Quetzal (GTQ)',6.5446);
INSERT INTO currencies (country_code, worth) VALUES ('Hong KongHong Kong Dollar (HKD)',6.9360);
INSERT INTO currencies (country_code, worth) VALUES ('HungaryHungarian Forint (HUF)',255.1488);
INSERT INTO currencies (country_code, worth) VALUES ('IcelandIcelandic Króna (ISK)',101.7270);
INSERT INTO currencies (country_code, worth) VALUES ('IndonesiaIndonesian Rupiah (IDR)',11414.8640);
INSERT INTO currencies (country_code, worth) VALUES ('IrelandEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('IsraelIsraeli New Sheqel (ILS)',3.3892);
INSERT INTO currencies (country_code, worth) VALUES ('ItalyEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('JamaicaJamaican Dollar (JMD)',112.3227);
INSERT INTO currencies (country_code, worth) VALUES ('JapanJapanese Yen (JPY)',98.7722);
INSERT INTO currencies (country_code, worth) VALUES ('JordanJordanian Dinar (JOD)',0.6301);
INSERT INTO currencies (country_code, worth) VALUES ('KenyaKenyan Shilling (KES)',87.1794);
INSERT INTO currencies (country_code, worth) VALUES ('Korea Republic ofSouth Korean Won (KRW)',1013.0114);
INSERT INTO currencies (country_code, worth) VALUES ('KuwaitKuwaiti Dinar (KWD)',0.2711);
INSERT INTO currencies (country_code, worth) VALUES ('LatviaEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('LithuaniaEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('LuxembourgEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('MalaysiaMalaysian Ringgit (MYR)',3.8707);
INSERT INTO currencies (country_code, worth) VALUES ('MaltaEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('MartiniqueEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('MayotteEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('MexicoMexican Peso (MXN)',18.2496);
INSERT INTO currencies (country_code, worth) VALUES ('MonacoEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('MontenegroEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('MoroccoMoroccan Dirham (MAD)',8.4048);
INSERT INTO currencies (country_code, worth) VALUES ('Netherlands AntillesAntillean Gulden (ANG)',1.5930);
INSERT INTO currencies (country_code, worth) VALUES ('NetherlandsEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('New ZealandNew Zealand Dollar (NZD)',1.2668);
INSERT INTO currencies (country_code, worth) VALUES ('NicaraguaNicaraguan Cordoba (NIO)',25.8660);
INSERT INTO currencies (country_code, worth) VALUES ('NorwayNorwegian Krone (NOK)',7.6572);
INSERT INTO currencies (country_code, worth) VALUES ('OmanOmani Rial (OMR)',0.3433);
INSERT INTO currencies (country_code, worth) VALUES ('PakistanPakistani Rupee (PKR)',94.3200);
INSERT INTO currencies (country_code, worth) VALUES ('PeruPeruvian Nuevo Sol (PEN)',2.9768);
INSERT INTO currencies (country_code, worth) VALUES ('PhilippinesPhilippine Peso (PHP)',43.2489);
INSERT INTO currencies (country_code, worth) VALUES ('PolandPolish Zloty (PLN)',3.6452);
INSERT INTO currencies (country_code, worth) VALUES ('PortugalEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('QatarQatari Riyal (QAR)',3.2378);
INSERT INTO currencies (country_code, worth) VALUES ('Russian FederationRussian Ruble (RUB)',53.9327);
INSERT INTO currencies (country_code, worth) VALUES ('Saudi ArabiaSaudi Riyal (SAR)',3.3343);
INSERT INTO currencies (country_code, worth) VALUES ('SingaporeSingapore Dollar (SGD)',1.2728);
INSERT INTO currencies (country_code, worth) VALUES ('SlovakiaEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('SloveniaEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('South AfricaSouth African Rand (ZAR)',12.2639);
INSERT INTO currencies (country_code, worth) VALUES ('SpainEuro (EUR)',0.8553);
INSERT INTO currencies (country_code, worth) VALUES ('SwedenSwedish Krona (SEK)',8.2713);
INSERT INTO currencies (country_code, worth) VALUES ('SwitzerlandSwiss Franc (CHF)',0.9093);
INSERT INTO currencies (country_code, worth) VALUES ('Taiwan Republic of ChinaNew Taiwan Dollar (TWD)',27.4836);
INSERT INTO currencies (country_code, worth) VALUES ('ThailandThai Baht (THB)',31.1877);
INSERT INTO currencies (country_code, worth) VALUES ('Trinidad and TobagoTrinidad and Tobago Dollar (TTD)',5.8323);
INSERT INTO currencies (country_code, worth) VALUES ('TunisiaTunisian Dinar (TND)',1.9981);
INSERT INTO currencies (country_code, worth) VALUES ('TurkeyTurkish New Lira (TRY)',2.9726);
INSERT INTO currencies (country_code, worth) VALUES ('United Arab EmiratesUAE Dirham (AED)',3.2660);
INSERT INTO currencies (country_code, worth) VALUES ('United KingdomBritish Pound (GBP)',0.7336);
INSERT INTO currencies (country_code, worth) VALUES ('UruguayUruguayan Peso (UYU)',25.2180);
INSERT INTO currencies (country_code, worth) VALUES ('VietnamVietnamese Dong (VND)',16950.0000);
